version: '3.1'

services:
  webapp:
    build:
      context: .
    networks:
      - backend
    ports:
        - "4000:4000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
    container_name: together-api
  db:
    image: postgres
    networks:
      - backend
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "./data/postges:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  logvolume01: {}

networks:
  backend:
