version: '3.1'

services:
  app:
    image: apmaros/together:latest
    networks:
        - outside
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  outside:
    external:
      name: "host"
