version: '3.1'

services:
  app:
    image: apmaros/together:latest
    networks:
        - outside
    environment:
        DB_USERNAME_FILE: '/run/secrets/db_username'
        DB_PASSWORD_FILE: '/run/secrets/db_password'
        JWT_SECRET_FILE: '/run/secrets/jwt_secret'
    secrets:
        - db_username
        - db_password
        - jwt_secret
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

secrets:
  db_username:
    external: true
  db_password:
    external: true
  jwt_secret:
    external: true

networks:
  outside:
    external:
      name: "host"
