name: deploy image

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: build and push docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        BUILD_VERSION: ${GITHUB_SHA::8}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        name: apmaros/together
        snapshot: true
        tag: latest

    - name: install ssh key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: deploy api
      run: docker --host ${{ secrets.DOCKER_SWARM_HOST }} stack deploy -c stack.yml together
